name: Hello CI

# Controls when the workflow will run
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install php
        run: |
          sudo add-apt-repository ppa:ondrej/php
          sudo apt update
          sudo apt install nginx php8.3-fpm

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Check php version
        run: |
          PHP=`which php`
          $PHP -v

      - name: Print message from file
        run: |
          PHP=`which php`
          $PHP hello.php
